name: Deploy Python Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Print changed files
        run: |
          echo "List of changed files:" 
          echo $(git diff --name-only HEAD^ HEAD)
      - name: Deploy Modified Files
        run: |
          # Constants
          S3_BUCKET=cipher-api-lambda
          S3_KEY=lambda.zip
          LAMBDA_FUNCTION_NAME=cipher-andresousa-pt
          # Download the existing zip from S3
          aws s3 cp s3://$S3_BUCKET/$S3_KEY existing_lambda.zip
          # Unzip the existing package
          unzip existing_lambda.zip
          # Copy only the modified .py files from the commit into the current directory
          # This will maintain their directory structure.
          for file in $(git diff-tree --no-commit-id --name-only -r HEAD); do
              if [[ $file == *.py ]]; then
                  # Copy the modified file
                  cp $file $file
                  # Print what you've done with the file
                  echo "Copied $file to $file"
                  echo "Content of $file after copying:"
                  cat $file
              fi
          done
          # Zip the directory again
          zip -r updated_lambda.zip .
          # Upload the updated zip to S3
          aws s3 cp updated_lambda.zip s3://$S3_BUCKET/$S3_KEY
          # Update Lambda function code
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY
          # Cleanup
          rm existing_lambda.zip updated_lambda.zip
